### ISSUE TITLE
[Readme request] Add links to Invisibros' Minecraft so that it's easier to find?

### ISSUE THREAD

**Issue by Darthagnon** [IridescentRose/MC3.0-Server#1]
Would it be possible to add links to Invisibros' Minecraft to the Readme, so that it's easier for people to find? Took a while for me to search it out (found it eventually through a link in the description of a spammy youtube channel)

- [Homepage](https://invisibros.weebly.com/minecraft-playstation-portable-edition.html)

- [YouTube](https://www.youtube.com/channel/UCFv_A01KSUi2p5GIo8hv7WA)

**Comment by IridescentRose** [comment]
He'll do it himself I think
